TimeoutAfter = 10

[HackerNews]
BaseURL = "https://hacker-news.firebaseio.com/v0/"

[StoriesCache]
DefaultExpirationInMinutes = 30
CleanupIntervalInMinutes = 10

[Github]
BaseURL = "https://api.github.com"

[Storage]
TimeoutAfter = 4096
Username = ""
Password = ""
Address = "localhost:27017"
Database = "chn"
Handler  = "mongodb"