//Code generated by xproto [v0.1.0], DO NOT EDIT.
//source: [chn.proto]
//Package [chn] is a generated stub package.
//This code was generated with github.com/donutloop/xservice [v0.1.0]
//It is generated from these files:
//	 [chn.proto]
//package [chn]

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/donutloop/xservice/framework/errors"
	"github.com/donutloop/xservice/framework/hooks"
	"github.com/donutloop/xservice/framework/server"
	"github.com/donutloop/xservice/framework/transport"
	"github.com/donutloop/xservice/framework/xcontext"
	"github.com/donutloop/xservice/framework/xhttp"
)

// //[StoryServicePathPrefix StoryService] is used for all URL paths on a %!s(MISSING) server.
//Requests are always: POST [StoryServicePathPrefix] /method
//It can be used in an HTTP mux to route requests
const StoryServicePathPrefix string = "/xservice/service.chn.StoryService/"

// 294 bytes of a gzipped FileDescriptorProto
var xserviceFileDescriptor0 = []byte{0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4e, 0xc3, 0x30, 0x10, 0x86, 0x95, 0xb8, 0x69, 0x9b, 0x2b, 0x42, 0xe8, 0x04, 0xc8, 0xaa, 0x10, 0x8a, 0x3a, 0xa0, 0x0c, 0x28, 0x43, 0x59, 0x60, 0x65, 0x62, 0x62, 0x48, 0x99, 0xd8, 0x52, 0xfb, 0x44, 0x2c, 0x1a, 0x3b, 0xb5, 0x5d, 0xa4, 0x3c, 0x34, 0xef, 0x80, 0xe2, 0x50, 0xc8, 0xd0, 0xed, 0xee, 0xbb, 0xcf, 0x67, 0xf9, 0x37, 0xa4, 0xa2, 0xd6, 0x45, 0x6b, 0x8d, 0x37, 0xb8, 0x70, 0x64, 0xbf, 0x94, 0xa0, 0x42, 0xd4, 0x7a, 0x75, 0x07, 0xf3, 0x8d, 0x37, 0xb6, 0x2b, 0x69, 0x8f, 0x4b, 0x98, 0x8b, 0xca, 0xd3, 0x87, 0xb1, 0x1d, 0x8f, 0xb2, 0x28, 0x4f, 0xcb, 0xbf, 0x7e, 0xf5, 0x04, 0xe9, 0xaf, 0xe7, 0x5a, 0xbc, 0x87, 0x99, 0xf3, 0xc6, 0x2a, 0x72, 0x3c, 0xca, 0x58, 0xbe, 0x58, 0x63, 0x31, 0xda, 0x59, 0x0c, 0xe2, 0x51, 0x59, 0x7d, 0x47, 0x90, 0x04, 0x84, 0xe7, 0x10, 0x6f, 0x8f, 0xab, 0xe3, 0x6d, 0x87, 0x19, 0x2c, 0x24, 0x39, 0x41, 0x5a, 0x56, 0xda, 0x3b, 0x1e, 0x67, 0x51, 0xce, 0xca, 0x31, 0xea, 0x4f, 0x28, 0xc9, 0x59, 0x18, 0xc4, 0x4a, 0x22, 0xc2, 0xe4, 0x53, 0x49, 0xc7, 0x27, 0x19, 0xcb, 0x59, 0x19, 0x6a, 0xbc, 0x84, 0xc4, 0x09, 0x63, 0x89, 0x27, 0x41, 0x1b, 0x9a, 0xde, 0xf4, 0x5d, 0x4b, 0x7c, 0x1a, 0x6e, 0x0b, 0x75, 0x6f, 0x7a, 0xe5, 0x77, 0xc4, 0x67, 0x01, 0x0e, 0x0d, 0x5e, 0x00, 0x3b, 0xd8, 0x1d, 0x9f, 0x07, 0xd6, 0x97, 0x78, 0x0b, 0x20, 0x4d, 0x53, 0x29, 0xfd, 0x5a, 0x35, 0xc4, 0xd3, 0x30, 0x18, 0x11, 0xbc, 0x81, 0xb4, 0x3e, 0x34, 0x95, 0x7e, 0x53, 0x0d, 0x71, 0x08, 0xe3, 0x7f, 0xb0, 0x7e, 0x81, 0xb3, 0xf0, 0xdc, 0xcd, 0x10, 0x09, 0x3e, 0xc2, 0x6c, 0x33, 0x44, 0x81, 0x57, 0x27, 0x72, 0xa2, 0xfd, 0xf2, 0xfa, 0x14, 0x76, 0xed, 0x73, 0xf2, 0xce, 0x44, 0xad, 0xb7, 0xd3, 0xf0, 0x6f, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x1c, 0x9d, 0x79, 0xc4, 0x01, 0x00, 0x00}

type StoryService interface {
	Stories(ctx context.Context, req *StoryReq) (*StoryResp, error)
}

// storyServiceJSONClient wraps an http.client and sends JSON objects
type storyServiceJSONClient struct {
	client transport.HTTPClient
	urls   [1]string
}

// Stories sends an StoryReq JSON object to the server
func (c *storyServiceJSONClient) Stories(ctx context.Context, in *StoryReq) (*StoryResp, error) {
	ctx = xcontext.WithPackageName(ctx, "service.chn")
	ctx = xcontext.WithServiceName(ctx, "StoryService")
	ctx = xcontext.WithMethodName(ctx, "Stories")
	out := new(StoryResp)
	err := transport.DoJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// storyServiceProtobufferClient wraps an http.client and sends Protobuffer objects
type storyServiceProtobufferClient struct {
	client transport.HTTPClient
	urls   [1]string
}

// Stories sends an StoryReq Protobuffer object to the server
func (c *storyServiceProtobufferClient) Stories(ctx context.Context, in *StoryReq) (*StoryResp, error) {
	ctx = xcontext.WithPackageName(ctx, "service.chn")
	ctx = xcontext.WithServiceName(ctx, "StoryService")
	ctx = xcontext.WithMethodName(ctx, "Stories")
	out := new(StoryResp)
	err := transport.DoProtobufferRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// storyServiceServer wraps an endpoint and implements http.Handler.
type storyServiceServer struct {
	StoryService
	hooks        *hooks.ServerHooks
	logErrorFunc transport.LogErrorFunc
}

func (s *storyServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	transport.WriteErrorAndTriggerHooks(ctx, resp, err, s.hooks)
}

// ServeHTTP implements http.Handler.
func (s *storyServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = xcontext.WithPackageName(ctx, "service.chn")
	ctx = xcontext.WithServiceName(ctx, "StoryService")
	ctx = xcontext.WithResponseWriter(ctx, resp)
	var err error
	ctx, err = transport.CallRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if req.Method != http.MethodPost {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		terr := errors.BadRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, terr)
		return
	}

	switch req.URL.Path {
	case "/xservice/service.chn.StoryService/Stories":
		s.serveStories(ctx, resp, req)
		return

	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		terr := errors.BadRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, terr)
		return
	}

}

// serveStories is used to set an decoder and encoder for a given content type
func (s *storyServiceServer) serveStories(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get(xhttp.ContentTypeHeader)
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	modifiedHeader := strings.ToLower(header[:i])
	modifiedHeader = strings.TrimSpace(modifiedHeader)
	if modifiedHeader == xhttp.ApplicationJson {
		s.serveStoriesContent(ctx, resp, req, transport.DecodeJSONRequest, transport.EncodeJSONResponse)
		return
	} else if modifiedHeader == xhttp.ApplicationProtobuf {
		s.serveStoriesContent(ctx, resp, req, transport.DecodePROTORequest, transport.EncodePROTOResponse)
		return
	} else {
		msg := fmt.Sprintf("unexpected Content-Type: %q", header)
		terr := errors.BadRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, terr)
	}
}

// serveStoriesContent sends object to requester
func (s *storyServiceServer) serveStoriesContent(ctx context.Context, resp http.ResponseWriter, req *http.Request, decodeRequest transport.DecodeRequestFunc, encodeResponse transport.EncodeResponseFunc) {
	var err error
	ctx = xcontext.WithMethodName(ctx, "Stories")
	ctx, err = transport.CallRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	defer transport.Closebody(req.Body, s.logErrorFunc)

	reqContent := new(StoryReq)
	if err := decodeRequest(ctx, req, reqContent); err != nil {
		s.logErrorFunc("%v", err)
		s.writeError(ctx, resp, err)
		return
	}
	endpointWrapper := func() (*StoryResp, error) {
		deferWrapper := func() {
			if r := recover(); r != nil {
				terr := errors.InternalError("Internal service panic")
				s.writeError(ctx, resp, terr)
				panic(r)
			}
		}
		defer deferWrapper()

		return s.Stories(ctx, reqContent)

	}
	respContent, err := endpointWrapper()
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		terr := errors.InternalError("received a nil * StoryResp, and nil error while calling Stories. nil responses are not supported")
		s.logErrorFunc("%v", err)
		s.writeError(ctx, resp, terr)
		return
	}
	ctx = transport.CallResponsePrepared(ctx, s.hooks)
	if err := encodeResponse(ctx, resp, respContent); err != nil {
		s.logErrorFunc("%v", err)
		s.writeError(ctx, resp, err)
		return
	}
	transport.CallResponseSent(ctx, s.hooks)
}

// ServiceDescriptor describes an service.
func (s *storyServiceServer) ServiceDescriptor() ([]uint8, int) {
	return xserviceFileDescriptor0, 0
}

// ProtocGenXServiceVersion returns which xservice version was used to generate that service
func (s *storyServiceServer) ProtocGenXServiceVersion() string {
	return "v0.1.0"
}

// NewStoryServiceJSONClient constructs a new client, which wraps the http.client and implements StoryService
func NewStoryServiceJSONClient(addr string, client transport.HTTPClient) StoryService {
	URLBase := transport.UrlBase(addr)
	prefix := URLBase + StoryServicePathPrefix
	urls := [1]string{
		prefix + "Stories",
	}
	httpClient, ok := client.(*http.Client)
	if ok == true {
		httpClient = transport.WithoutRedirects(httpClient)
		return &storyServiceJSONClient{
			client: httpClient,
			urls:   urls,
		}
	}
	return &storyServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

// NewStoryServiceProtobufferClient constructs a new client, which wraps the http.client and implements StoryService
func NewStoryServiceProtobufferClient(addr string, client transport.HTTPClient) StoryService {
	URLBase := transport.UrlBase(addr)
	prefix := URLBase + StoryServicePathPrefix
	urls := [1]string{
		prefix + "Stories",
	}
	httpClient, ok := client.(*http.Client)
	if ok == true {
		httpClient = transport.WithoutRedirects(httpClient)
		return &storyServiceProtobufferClient{
			client: httpClient,
			urls:   urls,
		}
	}
	return &storyServiceProtobufferClient{
		client: client,
		urls:   urls,
	}
}

// NewStoryServiceServer constructs a new server, and implements StoryService
func NewStoryServiceServer(svc StoryService, hooks *hooks.ServerHooks, errorFunc ...transport.LogErrorFunc) server.Server {
	server := &storyServiceServer{
		StoryService: svc,
		hooks:        hooks,
	}
	if len(errorFunc) == 1 {
		server.logErrorFunc = errorFunc[0]
	} else {
		server.logErrorFunc = log.Printf
	}
	return server
}
