FROM golang:alpine AS build-env
COPY ./ /go/src/github.com/donutloop/chn
WORKDIR /go/src/github.com/donutloop/chn/cmd/stories
RUN go build -o server

FROM alpine
COPY --from=build-env /go/src/github.com/donutloop/chn/cmd/stories/server /api/
ENTRYPOINT ["./api/server"]
